"""Core interfaces and types for the anonframework framework."""

from anonframework.core.channel import EventChannel, EventEnvelope
from anonframework.core.controller import (
    Controller,
    OptimizerFactory,
    RunResult,
    ScopeResolver,
    TargetFactory,
    TaskResult,
    ThreatModelResult,
)
from anonframework.core.interfaces import (
    NotApplicable,
    Optimizer,
    SecurityClaim,
    Target,
    Task,
)
from anonframework.core.middleware import (
    Middleware,
    compose,
    security_domain_filter,
    trajectory_recorder,
)
from anonframework.core.types import (
    ConfigSpec,
    Controllable,
    ControllableInjection,
    ControllableNoInjection,
    ControllablePostCallEvent,
    ControllablePreCallEvent,
    EvaluationResult,
    Event,
    EventHandler,
    EventResponse,
    EventResponseHandler,
    FilteredTrajectory,
    Goal,
    Observable,
    ObservableEvent,
    ObservableValue,
    QueryParam,
    QuerySpec,
    ReadableTrajectory,
    RunEndEvent,
    RunEndResponse,
    RunStartEvent,
    Scope,
    Score,
    SecurityDomain,
    SecurityDomainTag,
    Trajectory,
    get_domain,
    scope_includes,
)

__all__ = [
    # Channel
    "EventChannel",
    "EventEnvelope",
    # Controller
    "Controller",
    "OptimizerFactory",
    "RunResult",
    "ScopeResolver",
    "TargetFactory",
    "TaskResult",
    "ThreatModelResult",
    # Middleware
    "Middleware",
    "compose",
    "security_domain_filter",
    "trajectory_recorder",
    # Interfaces
    "NotApplicable",
    "Optimizer",
    "SecurityClaim",
    "Target",
    "Task",
    # Types
    "ConfigSpec",
    "Controllable",
    "ControllableInjection",
    "ControllableNoInjection",
    "ControllablePostCallEvent",
    "ControllablePreCallEvent",
    "EvaluationResult",
    "Event",
    "EventHandler",
    "EventResponse",
    "EventResponseHandler",
    "FilteredTrajectory",
    "Goal",
    "ObservableEvent",
    "Observable",
    "ObservableValue",
    "QueryParam",
    "QuerySpec",
    "ReadableTrajectory",
    "RunEndEvent",
    "RunEndResponse",
    "RunStartEvent",
    "Scope",
    "Score",
    "SecurityDomain",
    "SecurityDomainTag",
    "Trajectory",
    "get_domain",
    "scope_includes",
]
